	<div class="panel panel-default">
		<div class="panel-heading"
			style="font-family: 'Source Sans Pro'; font-size: 18px;">
			<h3>Sorry There is an error!</h3>
		</div>
		<div class="panel-body"
			style="font-family: 'Source Sans Pro'; font-size: 18px;">
			<p>
				Please contact us at: <a
					href="mailto:support@tomcathostingservice.com">support@tomcathostingservice.com</a><br />
				Or call our support number (425) 770-6899 <br /> Error Message: <span
					class="warning">$error$</span>
			</p>
		</div>
	</div>