
<div class="list-group">
	<a href="$context$manage-server.xhtml?id=$server.id$"
		class="list-group-item $manage$"> <span class="fa fa-server"></span>
		Manage $server.id$
	</a> <a href="$context$update-server-configuration.xhtml?id=$server.id$"
		class="list-group-item $update$"> <span class="fa fa-server"></span>
		Update Server Configuration
	</a> <a href="$context$rcon.xhtml?id=$server.id$"
		class="list-group-item $rcon$"> <span class="fa fa-server"></span>
		RCON
	</a> <a href="$context$view-logs.xhtml?id=$server.id$"
		class="list-group-item $log$"> <span class="fa fa-server"></span>
		View Server Logs
	</a>
	<a href="$context$manage-map.xhtml?id=$server.id$"
		class="list-group-item $managemap$"> <span class="fa fa-server"></span>
		Manage Map
	</a>
	<a href="$context$manage-plugin.xhtml?id=$server.id$"
		class="list-group-item $manageplugin$"> <span class="fa fa-server"></span>
		Manage Plugins
	</a>
</div>

