<footer id="footer">
	<div class="container">
		<div class="row">
			<div class="col-md-4 col-sm-6 margin30">
				<div class="footer-col">
					<h3>Sitemap</h3>
					<ul class="footer_list">
						<li ><a href="$context$tomcat-hosting.xhtml">Tomcat
							Hosting</a></li>
					<li ><a href="$context$tomcat-hosting.xhtml">Jsp Hosting</a></li>
					<li ><a href="$context$tomcat-hosting.xhtml">Java MySQL
							hosting</a></li>
					</ul>
					
				</div>
			</div>
			<!--footer col-->
			<div class="col-md-4 col-sm-6 margin30">
				<div class="footer-col">
					<h3>Contact</h3>

					<ul class="list-unstyled contact">
						<li><p>
								<strong><i class="fa fa-map-marker"></i> Address:</strong> 
								19011 36th Ave W Lynnwood, WA 98036 
							</p></li>
						<li><p>
								<strong><i class="fa fa-envelope"></i> Mail Us:</strong> <a
									href="#">support@tomcathostingservice.com</a>
							</p></li>
						<li>
							<p>
								<strong><i class="fa fa-phone"></i> Phone:</strong> (425)
								501-6401
							</p>
						</li>
						
					</ul>
					<ul class="list-inline social-1">
						<li><a href="#"><i class="fa fa-facebook"></i></a></li>
						<li><a href="#"><i class="fa fa-twitter"></i></a></li>
						<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
						<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
					</ul>
				</div>
			</div>
			<!--footer col-->

			<!--footer col-->
			<div class="col-md-4 col-sm-6 margin30">
				<div class="footer-col">
					<h3>Newsletter</h3>
					<p>To subscribe for news letters please add your email address
						here</p>
					
				</div>
			</div>
			<!--footer col-->

		</div>
	</div>
</footer>