<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<title>$title$</title>
<!-- Bootstrap -->
<link href="$context$bootstrap/css/bootstrap.min.css" rel="stylesheet">
<!-- custom css (blue color by default) -->

<link href="$context$css/custom.css" rel="stylesheet" type="text/css"
	media="screen">
	<link href="$context$css/prism.css" rel="stylesheet" type="text/css"
	media="screen">
	
<link href="$context$css/style.css" rel="stylesheet" type="text/css"
	media="screen">

<!-- font awesome for icons -->
<link href="$context$font-awesome-4.3.0/css/font-awesome.min.css"
	rel="stylesheet">
<!-- flex slider css -->
<link href="$context$css/flexslider.css" rel="stylesheet" type="text/css"
	media="screen">
<!-- animated css  -->
<link href="$context$css/animate.css" rel="stylesheet" type="text/css"
	media="screen">
<!--web fonts-->

<link href="css/fileinput.min.css" rel="stylesheet" type="text/css"
	media="screen">	

<!--Revolution slider css-->
<link href="$context$rs-plugin/css/settings.css" rel="stylesheet" type="text/css"
	media="screen">
<link href="$context$css/rev-style.css" rel="stylesheet" type="text/css"
	media="screen">
	
<!--google fonts-->


<link
	href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,400,300,600,700,800'
	rel='stylesheet' type='text/css'>
<!--owl carousel css-->
<link href="$context$css/owl.carousel.css" rel="stylesheet" type="text/css"
	media="screen">
<link href="$context$css/owl.theme.css" rel="stylesheet" type="text/css"
	media="screen">
<!--mega menu -->
<link href="$context$css/yamm.css" rel="stylesheet" type="text/css">
<!--popups css-->
<link href="$context$css/magnific-popup.css" rel="stylesheet" type="text/css">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
<link rel="shortcut icon" href="$context$images/favicon.ico" />


</head>