<div class="navbar navbar-default navbar-static-top yamm sticky"
	role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse"
				data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span> <span
					class="icon-bar"></span> <span class="icon-bar"></span> <span
					class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="index.xhtml"> <!--  <img src="img/logo.png" alt="Minecraft Control Panel">-->
				Minecraft Admin Control Panel
			</a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav navbar-right">
				<li class="$index$"><a href="$context$index.xhtml"><span
						class="glyphicon glyphicon-home"></span>&nbsp;Home</a></li>
			</ul>
		</div>
		<!--/.nav-collapse -->
	</div>
	<!--container-->
</div>
