<div id="header-top" class="hidden-xs">
	<div class="container">
		<div class="top-bar">
			<div class="pull-left sample-1right">
				<a><i class="fa fa-phone"></i> Any questions? Call us: <span
					class="colored-text">(425) 770-6899</span> </a> <a><i
					class="fa fa-envelope"></i> Mail us: <span class="colored-text">support@tomcathostingservice.com</span>
				</a>
			</div>
			<div class="pull-right">
			$if (loginmenu)$
				<a href="$context$login.xhtml"><i class="fa fa-sign-in"></i> Sign in</a>
			$else$
				<a href="$context$logout"><i class="fa fa-sign-out"></i> Sign out</a>
			$endif$
			<a href="$context$contact-us.xhtml"><i class="fa fa-envelope"></i> Contact Us</a>
					
			</div>
		</div>
	</div>
</div>